name: Build and Push Docker Images

on:
  push:
    branches:
      - review-3
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  SHA: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Проверка содержимого папки frontend
      - name: List files in frontend directory
        run: ls -l ./frontend

      # FRONTEND
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/film-react-nest:frontend-latest
            ghcr.io/${{ github.repository_owner }}/film-react-nest:frontend-${{ env.SHA }}

      # BACKEND
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/film-react-nest:backend-latest
            ghcr.io/${{ github.repository_owner }}/film-react-nest:backend-${{ env.SHA }}

      # NGINX
      - name: Build and push nginx image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/nginx
          file: ./frontend/nginx/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/film-react-nest:nginx-latest
            ghcr.io/${{ github.repository_owner }}/film-react-nest:nginx-${{ env.SHA }}

  deploy:
      runs-on: ubuntu-latest
      needs: build-and-push

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

#        - name: Copy docker-compose.yml to server
#          uses: appleboy/scp-action@v0.1.5
#          with:
#            host: ${{ secrets.SERVER_IP }}
#            username: ${{ secrets.SERVER_USER }}
#            key: ${{ secrets.SERVER_SSH_KEY }}
#            source: "docker-compose.yml"
#            target: "~/film-react-nest"

        - name: Copy full project to server
          uses: appleboy/scp-action@v0.1.5
          with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            source: "."  # весь репозиторий
            target: "~/film-react-nest"
            strip_components: 0

        - name: SSH into server and deploy
          uses: appleboy/ssh-action@v0.1.5
          with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              cd ~/film-react-nest
              docker-compose down
              docker-compose pull
              docker-compose up -d --build

        # Шаг для проверки состояния контейнеров после деплоя
        - name: Check docker-compose status
          uses: appleboy/ssh-action@v0.1.5
          with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              cd ~/film-react-nest
              docker-compose ps  # Выводит список контейнеров и их статус

        # Шаг для вывода логов контейнеров
        - name: Get logs from containers
          uses: appleboy/ssh-action@v0.1.5
          with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              cd ~/film-react-nest
              docker-compose logs --tail=100  # Выводит последние 100 строк логов для всех контейнеров